name: Python Mutation Test
env:
    PYTHONPATH: $PYTHONPATH:mydjangoproject
    DJANGO_SETTINGS_MODULE: mydjangoproject.settings
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |

        python -m pip install --upgrade pip
        pip install mutmut
        pip install -r requirements.txt
        python manage.py migrate
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest pytest-django
        pip install django
        pip install pony==0.7.14
        pip install pytest pytest-junitxml

    - name: Run mutation tests

      run: mutmut run --paths-to-mutate=evenorodd.py,find_num.py,test_num.py,mydjangoapp/tests --tests-dir= evenorodd.py,find_num.py,test_num.py,mydjangoapp/tests
    - name: Generate test report
      if: always()
      run: pytest --junitxml=test-results.xml
    - name: Publish test report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml

      

